### ISSUE TITLE
请问可以把坐标精细化吗

### ISSUE THREAD

**Issue by cjj0596** [GuoBinxs/MeituanSpider#1]
你好作者，我已经可以成功运行，跑到广州市的饭店，但是如果我想要特定某个区或者是某个商圈可以有方法做到吗？

**Comment by GuoBinxs** [comment]
您好，可以将该数据适当改小（ 4242640）
` g = int((max_lng - min_lng) * 102.3022 / 4242640)
    g1 = [round(min_lng + i * 4242640 / 102.3022) for i in range(1, g)]
    h = int((max_lat - min_lat) * 111.3195 / 4242640)
    h1 = [round(min_lat + i * 4242640 / 111.3195) for i in range(1, h)]`
